system kenshi_smoke3_small
{
    category                                    kenshi_particles
    technique 
    {
        material                                kenshi_smoke1
        default_particle_width                  1
        default_particle_height                 1
        default_particle_depth                  1
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point Emitter4
        {
            emission_rate                       1
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             1
                max                             5
            }
            all_particle_dimensions             dyn_random
            {
                min                             0.5
                max                             3
            }
            start_colour_range                  0.054902 0.054902 0.054902 0.235294
            end_colour_range                    0.054902 0.054902 0.054902 0.0392157
            colour                              0 0 0 0
        }
        affector                                Colour Affector27
        {
            time_colour                         0    1 1 1 0
            time_colour                         0.458696  1 1 1 1
            time_colour                         1    1 1 1 0.0156863
            colour_operation                    multiply
        }
        affector                                Scale Affector28
        {
            xyz_scale                           dyn_curved_linear
            {
                control_point                   0 0.556787
                control_point                   1 5.27701
            }
        }
        affector                                TextureRotator Affector3
        {
            rotation                            dyn_random
            {
                min                             0
                max                             360
            }
            rotation_speed                      0
        }
    }
}
