system kenshi_lightning_beam2B
{
    category                                    kenshi_particles
    technique 
    {
        material                                kenshi_lightningB
        default_particle_width                  1
        default_particle_height                 1
        default_particle_depth                  1
        renderer                                Billboard
        {
            billboard_type                      oriented_shape
            billboard_origin                    bottom_center
        }
        emitter                                 Line 
        {
            emission_rate                       200
            time_to_live                        1.4
            all_particle_dimensions             35
            direction                           0 0 0
            end                                 20 500 0
            min_increment                       30
            max_increment                       60
            max_deviation                       15
        }
        affector                                Align 
        {
            resize                              true
        }
        affector                                Colour Affector6
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.0652174  1 1 1 1
            time_colour                         0.186957  0.921569 0.866667 0.772549 1
            time_colour                         0.784783  0.235294 0.14902 0.333333 1
            time_colour                         1    0 0 0 1
        }
    }
    technique Technique3
    {
        material                                kenshi_dustparticle1
        renderer                                Billboard
        {
        }
        emitter                                 Line Emitter4
        {
            emission_rate                       100
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.6
            }
            velocity                            dyn_random
            {
                min                             0
                max                             10
            }
            all_particle_dimensions             dyn_random
            {
                min                             0.5
                max                             1
            }
            force_emission                      true
            end                                 20 500 0
            max_deviation                       5
        }
        emitter                                 SphereSurface Emitter6
        {
            emission_rate                       30
            angle                               360
            time_to_live                        dyn_random
            {
                min                             0.3
                max                             0.6
            }
            velocity                            dyn_random
            {
                min                             0
                max                             10
            }
            all_particle_dimensions             dyn_random
            {
                min                             0.5
                max                             1
            }
            force_emission                      true
            radius                              15
        }
        affector                                Colour Affector2
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.0804348  1 1 1 1
            time_colour                         0.254348  1 0 0.301961 1
            time_colour                         0.736957  0.494118 0.160784 0.00392157 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        affector                                LinearForce Affector3
        {
            enabled                             false
            force_vector                        0 -50 0
        }
    }
    technique Technique4
    {
        material                                kenshi_lightning2B
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
        }
        emitter                                 Point Emitter11
        {
            emission_rate                       3
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.3
            }
            velocity                            0
            all_particle_dimensions             dyn_random
            {
                min                             100
                max                             180
            }
            force_emission                      true
        }
        affector                                Colour Affector6
        {
            time_colour                         0    1 1 1 1
            time_colour                         0.0652174  1 1 1 1
            time_colour                         0.186957  0.882353 0.807843 0.658824 1
            time_colour                         0.784783  0.227451 0.14902 0.333333 1
            time_colour                         1    0 0 0 1
        }
        affector                                TextureRotator Affector14
        {
            rotation                            dyn_random
            {
                min                             0
                max                             360
            }
            rotation_speed                      0
        }
        affector                                Scale Affector6
        {
            xyz_scale                           dyn_curved_linear
            {
                control_point                   0.00184502 0
                control_point                   0.119926 3.5651
                control_point                   0.374539 5.90582
                control_point                   1 7.09418
            }
        }
    }
}
